# Generated by Django 4.2.2 on 2023-06-09 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parametres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autorite',
            options={'ordering': ['nom'], 'verbose_name': 'Autorité', 'verbose_name_plural': 'Autorités'},
        ),
        migrations.AlterModelOptions(
            name='domaineactivite',
            options={'ordering': ['nom'], 'verbose_name': "Domaine d'activité", 'verbose_name_plural': "Domaines d'activité"},
        ),
        migrations.AlterModelOptions(
            name='jourferie',
            options={'ordering': ['nom'], 'verbose_name': 'Jour Férié', 'verbose_name_plural': 'Jours Fériés'},
        ),
        migrations.AlterModelOptions(
            name='modepaiement',
            options={'ordering': ['nom'], 'verbose_name': 'Mode de Paiement', 'verbose_name_plural': 'Modes de Paiement'},
        ),
        migrations.AlterModelOptions(
            name='piece',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Pièce', 'verbose_name_plural': 'Pièces'},
        ),
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ['nom'], 'verbose_name': 'Profession', 'verbose_name_plural': 'Professions'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['nom'], 'verbose_name': 'Région', 'verbose_name_plural': 'Régions'},
        ),
        migrations.AlterField(
            model_name='autorite',
            name='adresse',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='autorite',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='autorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='autorite',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='autorite',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='autorite',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametres.pays', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='autorite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='domaineactivite',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='domaineactivite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='domaineactivite',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='domaineactivite',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='domaineactivite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametres.domaineactivite', verbose_name="Domaine d'activité"),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='nom',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='fonction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='jourferie',
            name='annuel',
            field=models.BooleanField(default=True, verbose_name='Annuel'),
        ),
        migrations.AlterField(
            model_name='jourferie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='jourferie',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='jourferie',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='jourferie',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='jourferie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='langue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='langue',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='langue',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='langue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='languepays',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='languepays',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='languepays',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='languepays',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='modepaiement',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='modepaiement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='modepaiement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ModesPaiement/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='modepaiement',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='modepaiement',
            name='nom',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='modepaiement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='indicatif',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Indicatif'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='langues',
            field=models.ManyToManyField(blank=True, default=None, to='parametres.languepays', verbose_name='Langues'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='longueur_numero',
            field=models.IntegerField(blank=True, null=True, verbose_name='Longueur du numéro'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='nationnalite',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nationalité'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='pays',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='autorite_delivrance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.autorite', verbose_name='Autorité de délivrance'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='date_delivrance',
            field=models.DateField(verbose_name='Date de délivrance'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='date_expiration',
            field=models.DateField(verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='piece',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Pieces/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='numero',
            field=models.CharField(max_length=50, verbose_name='Numéro'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='type_piece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametres.typepiece', verbose_name='Type de pièce'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametres.domaineactivite', verbose_name="Domaine d'activité"),
        ),
        migrations.AlterField(
            model_name='profession',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='profession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='region',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='region',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='region',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametres.pays', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='region',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='domaine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametres.domaineactivite', verbose_name="Domaine d'activité"),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='typepiece',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='typepiece',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='typepiece',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='typepiece',
            name='nom',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='typepiece',
            name='obligatoire',
            field=models.BooleanField(default=False, verbose_name='Obligatoire'),
        ),
        migrations.AlterField(
            model_name='typepiece',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='ville',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='ville',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='ville',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='ville',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='ville',
            name='pays',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametres.pays', verbose_name='Pays'),
        ),
        migrations.AlterField(
            model_name='ville',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametres.region', verbose_name='Région'),
        ),
        migrations.AlterField(
            model_name='ville',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
    ]
