from django.core.management.base import BaseCommand
from parametres.models import Pays

# fonction pour vider la table avant de la remplir
def clear_data_p():
    Pays.objects.all().delete()

class Command(BaseCommand):
    help = "Populate Pays table with initial data"

    def handle(self, *args, **kwargs):

        self.stdout.write('Vidage de la table Pays...')
        clear_data_p()

        pays_list = [
            {"nom": "Afghanistan", "code": "AF", "indicatif": "93"},
            {"nom": "Albanie", "code": "AL", "indicatif": "355"},
            {"nom": "Algérie", "code": "DZ", "indicatif": "213"},
            {"nom": "Allemagne", "code": "DE", "indicatif": "49"},
            {"nom": "Andorre", "code": "AD", "indicatif": "376"},
            {"nom": "Angola", "code": "AO", "indicatif": "244"},
            {"nom": "Antigua-et-Barbuda", "code": "AG", "indicatif": "1-268"},
            {"nom": "Arabie saoudite", "code": "SA", "indicatif": "966"},
            {"nom": "Argentine", "code": "AR", "indicatif": "54"},
            {"nom": "Arménie", "code": "AM", "indicatif": "374"},
            {"nom": "Australie", "code": "AU", "indicatif": "61"},
            {"nom": "Autriche", "code": "AT", "indicatif": "43"},
            {"nom": "Azerbaïdjan", "code": "AZ", "indicatif": "994"},
            {"nom": "Bahamas", "code": "BS", "indicatif": "1-242"},
            {"nom": "Bahreïn", "code": "BH", "indicatif": "973"},
            {"nom": "Bangladesh", "code": "BD", "indicatif": "880"},
            {"nom": "Barbade", "code": "BB", "indicatif": "1-246"},
            {"nom": "Bélarus", "code": "BY", "indicatif": "375"},
            {"nom": "Belgique", "code": "BE", "indicatif": "32"},
            {"nom": "Belize", "code": "BZ", "indicatif": "501"},
            {"nom": "Bénin", "code": "BJ", "indicatif": "229"},
            {"nom": "Bhoutan", "code": "BT", "indicatif": "975"},
            {"nom": "Bolivie", "code": "BO", "indicatif": "591"},
            {"nom": "Bosnie-Herzégovine", "code": "BA", "indicatif": "387"},
            {"nom": "Botswana", "code": "BW", "indicatif": "267"},
            {"nom": "Brésil", "code": "BR", "indicatif": "55"},
            {"nom": "Brunei", "code": "BN", "indicatif": "673"},
            {"nom": "Bulgarie", "code": "BG", "indicatif": "359"},
            {"nom": "Burkina Faso", "code": "BF", "indicatif": "226"},
            {"nom": "Burundi", "code": "BI", "indicatif": "257"},
            {"nom": "Cambodge", "code": "KH", "indicatif": "855"},
            {"nom": "Cameroun", "code": "CM", "indicatif": "237"},
            {"nom": "Canada", "code": "CA", "indicatif": "1"},
            {"nom": "Cap-Vert", "code": "CV", "indicatif": "238"},
            {"nom": "République centrafricaine", "code": "CF", "indicatif": "236"},
            {"nom": "Chili", "code": "CL", "indicatif": "56"},
            {"nom": "Chine", "code": "CN", "indicatif": "86"},
            {"nom": "Colombie", "code": "CO", "indicatif": "57"},
            {"nom": "Comores", "code": "KM", "indicatif": "269"},
            {"nom": "Congo", "code": "CG", "indicatif": "242"},
            {"nom": "République démocratique du Congo", "code": "CD", "indicatif": "243"},
            {"nom": "Cook Islands", "code": "CK", "indicatif": "682"},
            {"nom": "Costa Rica", "code": "CR", "indicatif": "506"},
            {"nom": "Côte d'Ivoire", "code": "CI", "indicatif": "225"},
            {"nom": "Croatie", "code": "HR", "indicatif": "385"},
            {"nom": "Cuba", "code": "CU", "indicatif": "53"},
            {"nom": "Curaçao", "code": "CW", "indicatif": "599"},
            {"nom": "Chypre", "code": "CY", "indicatif": "357"},
            {"nom": "République tchèque", "code": "CZ", "indicatif": "420"},
            {"nom": "Danemark", "code": "DK", "indicatif": "45"},
            {"nom": "Djibouti", "code": "DJ", "indicatif": "253"},
            {"nom": "Dominique", "code": "DM", "indicatif": "1-767"},
            {"nom": "République dominicaine", "code": "DO", "indicatif": "1-809, 1-829, 1-849"},
            {"nom": "Équateur", "code": "EC", "indicatif": "593"},
            {"nom": "Égypte", "code": "EG", "indicatif": "20"},
            {"nom": "Salvador", "code": "SV", "indicatif": "503"},
            {"nom": "Guinée équatoriale", "code": "GQ", "indicatif": "240"},
            {"nom": "Érythrée", "code": "ER", "indicatif": "291"},
            {"nom": "Estonie", "code": "EE", "indicatif": "372"},
            {"nom": "Éthiopie", "code": "ET", "indicatif": "251"},
            {"nom": "Îles Féroé", "code": "FO", "indicatif": "298"},
            {"nom": "Fidji", "code": "FJ", "indicatif": "679"},
            {"nom": "Finlande", "code": "FI", "indicatif": "358"},
            {"nom": "France", "code": "FR", "indicatif": "33"},
            {"nom": "Gabon", "code": "GA", "indicatif": "241"},
            {"nom": "Gambie", "code": "GM", "indicatif": "220"},
            {"nom": "Géorgie", "code": "GE", "indicatif": "995"},
            {"nom": "Ghana", "code": "GH", "indicatif": "233"},
            {"nom": "Grèce", "code": "GR", "indicatif": "30"},
            {"nom": "Grenade", "code": "GD", "indicatif": "1473"},
            {"nom": "Groenland", "code": "GL", "indicatif": "299"},
            {"nom": "Guadeloupe", "code": "GP", "indicatif": "590"},
            {"nom": "Guam", "code": "GU", "indicatif": "1671"},
            {"nom": "Guatemala", "code": "GT", "indicatif": "502"},
            {"nom": "Guinée", "code": "GN", "indicatif": "224"},
            {"nom": "Guinée-Bissau", "code": "GW", "indicatif": "245"},
            {"nom": "Guyana", "code": "GY", "indicatif": "592"},
            {"nom": "Guyane française", "code": "GF", "indicatif": "594"},
            {"nom": "Haïti", "code": "HT", "indicatif": "509"},
            {"nom": "Honduras", "code": "HN", "indicatif": "504"},
            {"nom": "Hong Kong", "code": "HK", "indicatif": "852"},
            {"nom": "Hongrie", "code": "HU", "indicatif": "36"},
            {"nom": "Île Christmas", "code": "CX", "indicatif": "61"},
            {"nom": "Île de Man", "code": "IM", "indicatif": "44"},
            {"nom": "Île Maurice", "code": "MU", "indicatif": "230"},
            {"nom": "Îles Caïmans", "code": "KY", "indicatif": "1345"},
            {"nom": "Îles Cocos (Keeling)", "code": "CC", "indicatif": "61"},
            {"nom": "Îles Cook", "code": "CK", "indicatif": "682"},
            {"nom": "Îles Féroé", "code": "FO", "indicatif": "298"},
            {"nom": "Îles Mariannes du Nord", "code": "MP", "indicatif": "1670"},
            {"nom": "Îles Marshall", "code": "MH", "indicatif": "692"},
            {"nom": "Îles Pitcairn", "code": "PN", "indicatif": "870"},
            {"nom": "Îles Salomon", "code": "SB", "indicatif": "677"},
            {"nom": "Îles Turks et Caïques", "code": "TC", "indicatif": "1649"},
            {"nom": "Îles Vierges américaines", "code": "VI", "indicatif": "1340"},
            {"nom": "Îles Vierges britanniques", "code": "VG", "indicatif": "1284"},
            {"nom": "Inde", "code": "IN", "indicatif": "91"},
            {"nom": "Indonésie", "code": "ID", "indicatif": "62"},
            {"nom": "Irak", "code": "IQ", "indicatif": "964"},
            {"nom": "Iran", "code": "IR", "indicatif": "98"},
            {"nom": "Irlande", "code": "IE", "indicatif": "353"},
            {"nom": "Islande", "code": "IS", "indicatif": "354"},
            {"nom": "Israël", "code": "IL", "indicatif": "972"},
            {"nom": "Italie", "code": "IT", "indicatif": "39"},
            {"nom": "Jamaïque", "code": "JM", "indicatif": "1876"},
            {"nom": "Japon", "code": "JP", "indicatif": "81"},
            {"nom": "Jordanie", "code": "JO", "indicatif": "962"},
            {"nom": "Kazakhstan", "code": "KZ", "indicatif": "7"},
            {"nom": "Kenya", "code": "KE", "indicatif": "254"},
            {"nom": "Kirghizistan", "code": "KG", "indicatif": "996"},
            {"nom": "Kiribati", "code": "KI", "indicatif": "686"},
            {"nom": "Koweït", "code": "KW", "indicatif": "965"},
            {"nom": "Laos", "code": "LA", "indicatif": "856"},
            {"nom": "Lesotho", "code": "LS", "indicatif": "266"},
            {"nom": "Lettonie", "code": "LV", "indicatif": "371"},
            {"nom": "Liban", "code": "LB", "indicatif": "961"},
            {"nom": "Liberia", "code": "LR", "indicatif": "231"},
            {"nom": "Libye", "code": "LY", "indicatif": "218"},
            {"nom": "Liechtenstein", "code": "LI", "indicatif": "423"},
            {"nom": "Lituanie", "code": "LT", "indicatif": "370"},
            {"nom": "Luxembourg", "code": "LU", "indicatif": "352"},
            {"nom": "Macao", "code": "MO", "indicatif": "853"},
            {"nom": "Macédoine", "code": "MK", "indicatif": "389"},
            {"nom": "Madagascar", "code": "MG", "indicatif": "261"},
            {"nom": "Malaisie", "code": "MY", "indicatif": "60"},
            {"nom": "Malawi", "code": "MW", "indicatif": "265"},
            {"nom": "Maldives", "code": "MV", "indicatif": "960"},
            {"nom": "Mali", "code": "ML", "indicatif": "223"},
            {"nom": "Malte", "code": "MT", "indicatif": "356"},
            {"nom": "Mariannes du Nord", "code": "MP", "indicatif": "1670"},
            {"nom": "Maroc", "code": "MA", "indicatif": "212"},
            {"nom": "Marshall, Îles", "code": "MH", "indicatif": "692"},
            {"nom": "Martinique", "code": "MQ", "indicatif": "596"},
            {"nom": "Maurice", "code": "MU", "indicatif": "230"},
            {"nom": "Mauritanie", "code": "MR", "indicatif": "222"},
            {"nom": "Mayotte", "code": "YT", "indicatif": "262"},
            {"nom": "Mexique", "code": "MX", "indicatif": "52"},
            {"nom": "Micronésie, États fédérés de", "code": "FM", "indicatif": "691"},
            {"nom": "Moldova, République de", "code": "MD", "indicatif": "373"},
            {"nom": "Monaco", "code": "MC", "indicatif": "377"},
            {"nom": "Mongolie", "code": "MN", "indicatif": "976"},
            {"nom": "Montserrat", "code": "MS", "indicatif": "1664"},
            {"nom": "Monténégro", "code": "ME", "indicatif": "382"},
            {"nom": "Mozambique", "code": "MZ", "indicatif": "258"},
            {"nom": "Myanmar", "code": "MM", "indicatif": "95"},
            {"nom": "Namibie", "code": "NA", "indicatif": "264"},
            {"nom": "Nauru", "code": "NR", "indicatif": "674"},
            {"nom": "Népal", "code": "NP", "indicatif": "977"},
            {"nom": "Nicaragua", "code": "NI", "indicatif": "505"},
            {"nom": "Niger", "code": "NE", "indicatif": "227"},
            {"nom": "Nigéria", "code": "NG", "indicatif": "234"},
            {"nom": "Niue", "code": "NU", "indicatif": "683"},
            {"nom": "Norfolk, Île", "code": "NF", "indicatif": "672"},
            {"nom": "Norvège", "code": "NO", "indicatif": "47"},
            {"nom": "Nouvelle-Calédonie", "code": "NC", "indicatif": "687"},
            {"nom": "Nouvelle-Zélande", "code": "NZ", "indicatif": "64"},
            {"nom": "Oman", "code": "OM", "indicatif": "968"},
            {"nom": "Ouganda", "code": "UG", "indicatif": "256"},
            {"nom": "Ouzbékistan", "code": "UZ", "indicatif": "998"},
            {"nom": "Pakistan", "code": "PK", "indicatif": "92"},
            {"nom": "Palaos", "code": "PW", "indicatif": "680"},
            {"nom": "Palestinien occupé, Territoire", "code": "PS", "indicatif": "970"},
            {"nom": "Panama", "code": "PA", "indicatif": "507"},
            {"nom": "Papouasie-Nouvelle-Guinée", "code": "PG", "indicatif": "675"},
            {"nom": "Paraguay", "code": "PY", "indicatif": "595"},
            {"nom": "Pays-Bas", "code": "NL", "indicatif": "31"},
            {"nom": "Pérou", "code": "PE", "indicatif": "51"},
            {"nom": "Philippines", "code": "PH", "indicatif": "63"},
            {"nom": "Pologne", "code": "PL", "indicatif": "48"},
            {"nom": "Polynésie française", "code": "PF", "indicatif": "689"},
            {"nom": "Porto Rico", "code": "PR", "indicatif": "1-787, 1-939"},
            {"nom": "Portugal", "code": "PT", "indicatif": "351"},
            {"nom": "Qatar", "code": "QA", "indicatif": "974"},
            {"nom": "République centrafricaine", "code": "CF", "indicatif": "236"},
            {"nom": "République démocratique du Congo", "code": "CD", "indicatif": "243"},
            {"nom": "République dominicaine", "code": "DO", "indicatif": "1-809, 1-829, 1-849"},
            {"nom": "République tchèque", "code": "CZ", "indicatif": "420"},
            {"nom": "Réunion", "code": "RE", "indicatif": "262"},
            {"nom": "Roumanie", "code": "RO", "indicatif": "40"},
            {"nom": "Royaume-Uni", "code": "GB", "indicatif": "44"},
            {"nom": "Russie", "code": "RU", "indicatif": "7"},
            {"nom": "Rwanda", "code": "RW", "indicatif": "250"},
            {"nom": "Saint-Christophe-et-Niévès", "code": "KN", "indicatif": "1-869"},
            {"nom": "Saint-Marin", "code": "SM", "indicatif": "378"},
            {"nom": "Saint-Martin", "code": "MF", "indicatif": "590"},
            {"nom": "Saint-Pierre-et-Miquelon", "code": "PM", "indicatif": "508"},
            {"nom": "Saint-Vincent-et-les-Grenadines", "code": "VC", "indicatif": "1-784"},
            {"nom": "Sainte-Hélène, Ascension et Tristan da Cunha", "code": "SH", "indicatif": "290"},
            {"nom": "Sainte-Lucie", "code": "LC", "indicatif": "1-758"},
            {"nom": "Salomon", "code": "SB", "indicatif": "677"},
            {"nom": "Salvador", "code": "SV", "indicatif": "503"},
            {"nom": "Samoa", "code": "WS", "indicatif": "685"},
            {"nom": "Samoa américaines", "code": "AS", "indicatif": "1-684"},
            {"nom": "Sao Tomé-et-Principe", "code": "ST", "indicatif": "239"},
            {"nom": "Sénégal", "code": "SN", "indicatif": "221"},
            {"nom": "Serbie", "code": "RS", "indicatif": "381"},
            {"nom": "Seychelles", "code": "SC", "indicatif": "248"},
            {"nom": "Sierra Leone", "code": "SL", "indicatif": "232"},
            {"nom": "Singapour", "code": "SG", "indicatif": "65"},
            {"nom": "Slovaquie", "code": "SK", "indicatif": "421"},
            {"nom": "Slovénie", "code": "SI", "indicatif": "386"},
            {"nom": "Somalie", "code": "SO", "indicatif": "252"},
            {"nom": "Soudan", "code": "SD", "indicatif": "249"},
            {"nom": "Soudan du Sud", "code": "SS", "indicatif": "211"},
            {"nom": "Sri Lanka", "code": "LK", "indicatif": "94"},
            {"nom": "Suède", "code": "SE", "indicatif": "46"},
            {"nom": "Suisse", "code": "CH", "indicatif": "41"},
            {"nom": "Suriname", "code": "SR", "indicatif": "597"},
            {"nom": "Swaziland", "code": "SZ", "indicatif": "268"},
            {"nom": "Syrie", "code": "SY", "indicatif": "963"},
            {"nom": "Tadjikistan", "code": "TJ", "indicatif": "992"},
            {"nom": "Tanzanie", "code": "TZ", "indicatif": "255"},
            {"nom": "Tchad", "code": "TD", "indicatif": "235"},
            {"nom": "Thaïlande", "code": "TH", "indicatif": "66"},
            {"nom": "Timor-Leste", "code": "TL", "indicatif": "670"},
            {"nom": "Togo", "code": "TG", "indicatif": "228"},
            {"nom": "Tonga", "code": "TO", "indicatif": "676"},
            {"nom": "Trinité-et-Tobago", "code": "TT", "indicatif": "1868"},
            {"nom": "Tunisie", "code": "TN", "indicatif": "216"},
            {"nom": "Turkménistan", "code": "TM", "indicatif": "993"},
            {"nom": "Turquie", "code": "TR", "indicatif": "90"},
            {"nom": "Tuvalu", "code": "TV", "indicatif": "688"},
            {"nom": "Ukraine", "code": "UA", "indicatif": "380"},
            {"nom": "Uruguay", "code": "UY", "indicatif": "598"},
            {"nom": "Vanuatu", "code": "VU", "indicatif": "678"},
            {"nom": "Venezuela", "code": "VE", "indicatif": "58"},
            {"nom": "Viêt Nam", "code": "VN", "indicatif": "84"},
            {"nom": "Wallis-et-Futuna", "code": "WF", "indicatif": "681"},
            {"nom": "Yémen", "code": "YE", "indicatif": "967"},
            {"nom": "Zambie", "code": "ZM", "indicatif": "260"},
            {"nom": "Zimbabwe", "code": "ZW", "indicatif": "263"}
        ]
        
        for pays_data in pays_list:
            # Vérifier si la langue existe déjà dans la base de données
            if Pays.objects.filter(code=pays_data['code']).exists():
                self.stdout.write(self.style.WARNING(f'Pays "{pays_obj}" existe déjà'))
            else:
                pays_obj, created = Pays.objects.get_or_create(nom=pays_data['nom'], code=pays_data['code'], indicatif=pays_data['indicatif'])
                self.stdout.write(self.style.SUCCESS(f'Pays "{pays_obj}" ajouté avec succès'))

